name: build-env
channels:
- defaults
- conda-forge
- cantera
dependencies:
  - numpy>=1.13.1
  - cantera>=2.3.0
  - networkx
  - pytables
  - pyyaml
  - sphinx
  - sphinxcontrib-bibtex
  - nbsphinx
  - ipython
  - conda-build
  - anaconda-client
  - doctr
